name: bier-prod

services:
  app:
    build:
      target: prod
    restart: always
    networks:
      - bier_net

  nginx:
    image: bier-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx-prod
    restart: always
    networks:
      - bier_net
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.bier.rule=Host(`tools.teddybier.com.br`)"
      - "traefik.http.routers.bier.entrypoints=web"
      - "traefik.http.services.bier.loadbalancer.server.port=80"
    depends_on:
      - app

  mysql:
    restart: always
    networks:
      - bier_net

  redis:
    restart: always
    networks:
      - bier_net

networks:
  bier_net:
    driver: bridge
  web:
    external: true
