services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bier_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        environment:
            - PHP_OPCACHE_ENABLE=0
        networks:
            - bier_net
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:alpine
        container_name: bier_nginx
        restart: unless-stopped
        ports:
            - "8010:80"                           # http://localhost:8010
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - bier_net
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: bier_mysql
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: teddy_bier_tools
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: bier
            MYSQL_PASSWORD: bier
        volumes:
            - bier_mysql_data:/var/lib/mysql
        networks:
            - bier_net

    redis:
        image: redis:7-alpine
        container_name: bier_redis
        restart: unless-stopped
        ports:
            - "6380:6379"
        volumes:
            - bier_redis_data:/data
        networks:
            - bier_net

    node:
        image: node:20-alpine
        container_name: bier_node
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "5173:5173"
        # Ao parar o container (docker compose down), o ; garante que o hot file é removido
        command: sh -c "npm install && npm run dev -- --host; rm -f /var/www/public/hot"
        networks:
            - bier_net
        profiles:
            - dev

networks:
    bier_net:
        driver: bridge

volumes:
    bier_mysql_data:
    bier_redis_data:
